package com.example.foodvillage2205.view.composables

import com.example.foodvillage2205.model.entities.Post

object FakeFoodData {

    val foodList = listOf(
        Post(
            id = "1",
            title = "Rice Snacks",
            imageUrl = "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTR8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
            description = "Our Rice Crisps come in a delicious variety of flavours to satisfy your snack cravings any time of day.",
            userId = "Rice Moon",
            email = "riceSnack@gmail.com",
            phone = "+1(388)743-8957",
            street = "2 Starling Circle",
            city = "Vancouver",
            province = "BC",
            postalCode = "S9V 0Z7",
        ),
        Post(
            id = "2",
            title = "Fruit Salad",
            imageUrl = "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8Nnx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
            description = "Our Rice Crisps come in a delicious variety of flavours to satisfy your snack cravings any time of day.",
            userId = "Rice Moon",
            email = "riceSnack@gmail.com",
            phone = "+1(388)743-8957",
            street = "2 Starling Circle",
            city = "Vancouver",
            province = "BC",
            postalCode = "S9V 0Z7",
        ),
        Post(
            id = "3",
            title = "Whiskey",
            imageUrl = "https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjF8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
            description = "Our Rice Crisps come in a delicious variety of flavours to satisfy your snack cravings any time of day.",
            userId = "Rice Moon",
            email = "riceSnack@gmail.com",
            phone = "+1(388)743-8957",
            street = "2 Starling Circle",
            city = "Vancouver",
            province = "BC",
            postalCode = "S9V 0Z7",
        ),
        Post(
            id = "4",
            title = "Hot Curry",
            imageUrl = "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjR8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
            description = "Our Rice Crisps come in a delicious variety of flavours to satisfy your snack cravings any time of day.",
            userId = "Rice Moon",
            email = "riceSnack@gmail.com",
            phone = "+1(388)743-8957",
            street = "2 Starling Circle",
            city = "Vancouver",
            province = "BC",
            postalCode = "S9V 0Z7",
        ),
        Post(
            id = "5",
            title = "Jhon Steak",
            imageUrl = "https://images.unsplash.com/photo-1432139555190-58524dae6a55?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MzZ8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
            description = "Our Rice Crisps come in a delicious variety of flavours to satisfy your snack cravings any time of day.",
            userId = "Rice Moon",
            email = "riceSnack@gmail.com",
            phone = "+1(388)743-8957",
            street = "2 Starling Circle",
            city = "Vancouver",
            province = "BC",
            postalCode = "S9V 0Z7",
        ),
        Post(
            id = "6",
            title = "Avocado",
            imageUrl = "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8NTN8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
            description = "Our Rice Crisps come in a delicious variety of flavours to satisfy your snack cravings any time of day.",
            userId = "Rice Moon",
            email = "riceSnack@gmail.com",
            phone = "+1(388)743-8957",
            street = "2 Starling Circle",
            city = "Vancouver",
            province = "BC",
            postalCode = "S9V 0Z7",
        ),
        Post(
            id = "7",
            title = "Breakfast-Strawberry",
            imageUrl = "https://images.unsplash.com/photo-1504113888839-1c8eb50233d3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8NjB8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
            description = "Our Rice Crisps come in a delicious variety of flavours to satisfy your snack cravings any time of day.",
            userId = "Rice Moon",
            email = "riceSnack@gmail.com",
            phone = "+1(388)743-8957",
            street = "2 Starling Circle",
            city = "Vancouver",
            province = "BC",
            postalCode = "S9V 0Z7",
        ),
        Post(
            id = "8",
            title = "Kenny's Dumplings",
            imageUrl = "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8Njd8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
            description = "Our Rice Crisps come in a delicious variety of flavours to satisfy your snack cravings any time of day.",
            userId = "Rice Moon",
            email = "riceSnack@gmail.com",
            phone = "+1(388)743-8957",
            street = "2 Starling Circle",
            city = "Vancouver",
            province = "BC",
            postalCode = "S9V 0Z7",
        ),
        Post(
            id = "9",
            title = "Broccoli meat",
            imageUrl = "https://images.unsplash.com/photo-1539136788836-5699e78bfc75?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8ODd8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
            description = "Our Rice Crisps come in a delicious variety of flavours to satisfy your snack cravings any time of day.",
            userId = "Rice Moon",
            email = "riceSnack@gmail.com",
            phone = "+1(388)743-8957",
            street = "2 Starling Circle",
            city = "Vancouver",
            province = "BC",
            postalCode = "S9V 0Z7",
        ),
        Post(
            id = "10",
            title = "Jerry Burger",
            imageUrl = "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8OTd8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
            description = "Our Rice Crisps come in a delicious variety of flavours to satisfy your snack cravings any time of day.",
            userId = "Rice Moon",
            email = "riceSnack@gmail.com",
            phone = "+1(388)743-8957",
            street = "2 Starling Circle",
            city = "Vancouver",
            province = "BC",
            postalCode = "S9V 0Z7",
        ),
    )
}